apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: repo1
  name: repo1
  namespace: exam-zoyirjon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: repo1
    spec:
      containers:
      - image: zoyirjon/repo-1:v1
        name: repo-1
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: DB_URI
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: info
              key: env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: info
              key: log_leveI
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: info
              key: grpc_port
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources: {}
status: {}
